### ISSUE TITLE
UI enhancement for favorites

### ISSUE THREAD

**Issue by rachbrooke** [dhis2/dhis2-visualizer#12]
Currently a favorite is only available in the app in which it was created.  

Would like a favorite to be accessed/modified/shared in several apps. 

For example a favorite created in the data visualizer app could be displayed in the charts app, events app, GIS...  Possibility to toggle in that respect while keeping the same favorite open.

This would make the experience more meaningful to the user.

**Comment by larshelge** [comment]
Not so feasible given that we have separate apps.
