### ISSUE TITLE
Wrong link for Open in this app

### ISSUE THREAD

**Issue by larshelge** [dhis2/dhis2-visualizer#14]
Under Favorites > Get link > Open in this app. The link is pointing to pivot table app. Should point to visualizer app.

Version: 2.25 stable, master.

![link](https://cloud.githubusercontent.com/assets/908206/19435960/cd0888c6-946d-11e6-9b85-cb8b40d4f583.png)

**Comment by janhenrikoverland** [comment]
Fixed:
- 2.25
- 2.26 snapshot
