### ISSUE TITLE
(2.24) Cannot load data elements

### ISSUE THREAD

**Issue by larshelge** [dhis2/dhis2-visualizer#8]
Applies to 2.24 stable.

Under Data section, select either All data elements or a data element group.

The server request crashes and no data elements are listed in the available list.

Happens because the app tries to filter on valueType enum, which is not supported.

<pre>&filter=valueType:in:[BOOLEAN,TRUE_ONLY,TEXT,LONG_TEXT,LETTER,...</pre>

**Comment by janhenrikoverland** [comment]
Fixed in 2.24
